# -*- coding: utf-8 -*-
"""1d histogram.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/17My7i4mq5oqTM2AB-XzpfLSy8eDpCMfd
"""

from google.colab import files

uploaded = files.upload()

for fn in uploaded.keys():
  print('User uploaded file "{name}" with length {length} bytes'.format(
      name=fn, length=len(uploaded[fn])))

from google.colab import files

uploaded = files.upload()

for fn in uploaded.keys():
  print('User uploaded file "{name}" with length {length} bytes'.format(
      name=fn, length=len(uploaded[fn])))

import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd

d1 = np.loadtxt("example_1.txt")
d2 = np.loadtxt("example_2.txt")
print(d1.shape, d2.shape)

plt.hist(d1, label='D1')
plt.hist(d2, label='D2')
plt.legend()
plt.ylabel("counts");

bins = np.linspace(min(d1.min(),d2.min()), max(d1.max(), d2.max()), 50)
counts1,bins, _ = plt.hist(d1, bins=10, label="D1")
plt.hist(d2, bins=bins, label="D2")
plt.legend()
plt.ylabel("counts");

bins = np.linspace(min(d1.min(),d2.min()), max(d1.max(), d2.max()), 50)
counts1,bins, _ = plt.hist(d1, bins=10, label="D1", density=True)
plt.hist(d2, bins=bins, label="D2", density=True)
plt.legend()
plt.ylabel("Probability");

bins = np.linspace(min(d1.min(),d2.min()), max(d1.max(), d2.max()), 50)
plt.hist([d1, d2], bins=bins ,label="Stacked", density=True,histtype="barstacked",alpha=0.5)
plt.hist(d1, bins=bins, label="D1", density=True, histtype="step", lw=1)
plt.hist(d2, bins=bins, label="D2", density=True, histtype="step", ls=":")
plt.legend()
plt.ylabel("Probability");