# -*- coding: utf-8 -*-
"""Descriptive Analytics .ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1l9SOdQZEHwt825fOfEpZVqV9sYcx9xLk
"""

from google.colab import files

uploaded = files.upload()

for fn in uploaded.keys():
  print('User uploaded file "{name}" with length {length} bytes'.format(
      name=fn, length=len(uploaded[fn])))

import pandas as pd

ipl_auction_df = pd.read_csv('IPL IMB381IPL2013.csv')

type(ipl_auction_df)

pd.set_option('display.max_columns', 7)
ipl_auction_df.head(5)

list(ipl_auction_df.columns)

ipl_auction_df.head(5).transpose()

ipl_auction_df.shape

ipl_auction_df.info()

ipl_auction_df[0:5]

ipl_auction_df[-5:]

ipl_auction_df['PLAYER NAME'][0:5]

ipl_auction_df.iloc[4:9, 1:4]

ipl_auction_df.COUNTRY.value_counts()

ipl_auction_df.COUNTRY.value_counts(normalize='TRUE')*100

pd.crosstab(ipl_auction_df['AGE'], ipl_auction_df['PLAYING ROLE'])

ipl_auction_df[['PLAYER NAME', 'SOLD PRICE']].sort_values('SOLD PRICE')[0:5]

ipl_auction_df[['PLAYER NAME',  'SOLD PRICE']].sort_values('SOLD PRICE', ascending = 'False')[0:5]

ipl_auction_df.groupby('AGE')['SOLD PRICE'].mean()

soldprice_by_age = ipl_auction_df.groupby(['AGE', 'PLAYING ROLE'])['SOLD PRICE'].mean().reset_index()
print(soldprice_by_age)

ipl_auction_df[ipl_auction_df['SIXERS'] > 80][['PLAYER NAME', 'SIXERS']]

# Commented out IPython magic to ensure Python compatibility.
import matplotlib.pyplot as plt
import seaborn as sn
# %matplotlib inline

sn.barplot(x= 'AGE', y=  'SOLD PRICE', data = soldprice_by_age)

plt.hist( ipl_auction_df['SOLD PRICE']);

plt.hist(ipl_auction_df['SOLD PRICE'], bins = 20 );

sn.distplot(ipl_auction_df['SOLD PRICE']);

box = sn.boxplot(ipl_auction_df['SOLD PRICE']);

box = plt.boxplot(ipl_auction_df['SOLD PRICE']);

ipl_batsman_df = ipl_auction_df[ipl_auction_df['PLAYING ROLE'] == 'Batsman']

plt.scatter(x = ipl_batsman_df.SIXERS, 
            y = ipl_batsman_df['SOLD PRICE']);

sn.regplot(x = 'SIXERS',
           y = 'SOLD PRICE',
           data = ipl_auction_df);

influential_features = ['SR-B', 'AVE', 'SIXERS', 'SOLD PRICE']

sn.pairplot(ipl_auction_df[influential_features], size = 2)

ipl_auction_df[influential_features].corr()

sn.heatmap(ipl_auction_df[influential_features].corr(), annot=True);

